---
- name: connection
  hosts: jenkins
  become: yes

  # #ansible-playbook playbook4.yml -i hosts.ini
  # #ansible-playbook playbook4.yml -i hosts.ini --syntax-check
  # #ansible-playbook playbook4.yml -i hosts.ini --ssh-common-args='-o StrictHostKeyChecking=no'
  # #ansible-playbook install_docker.yml -i hosts.ini --ssh-common-args='-o StrictHostKeyChecking=no' -v
  tasks:
    - name: Updateapt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: install jq
      apt: 
        name: jq
        state: present

    - name: install software-properties-common
      apt: 
        name: software-properties-common
        state: present

    - name: Add source repository into sources list
      shell: add-apt-repository --yes --update ppa:ansible/ansible
      become: yes
    
    - name: install ansible
      apt: 
        name: ansible
        state: present

    # You can use shell to run other executables to perform actions inline
    - name: install terraform
      ansible.builtin.shell: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        exit 0
    
    - name: install aws
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        yes | unzip awscliv2.zip
        yes | sudo ./aws/install
        echo aws --version
        exit 0      
        
    - name: configure aws
      shell: |
          aws configure set aws_access_key_id AKIA3ILFTMUJSCSHIIOM
          aws configure set aws_secret_access_key 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
          aws configure set default.region eu-west-2
          aws configure set default.output json
          exit 0
      register: shell_output
      tags:
        - always
      become: yes
      become_user: ubuntu
    - debug: var=shell_output
        
      #   executable: /usr/bin/expect
      # delegate_to: localhost



